trigger:

- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# dotnet

- task: DotNetCoreCLI@2
  displayName: .Net Core Restore
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: .Net Core Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release' # Update this to match your need

- task: DotNetCoreCLI@2
  displayName: .Net Core Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  displayName: Artifacts Publish
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'murieljoselima/api-service-labmark'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'