trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'murieljoselima/api-service-labmark'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'