version: '3.4'

services:
  api-application-labmark:
    image: murieljoselima/application-labmark:latest
    container_name: application-labmark
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    mem_limit: 600m
    mem_reservation: 350m
    networks:
      - development-network
    ports:
      - "4200:80"
    depends_on:
      - sql-server
  sql-server:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: db-labmark
    mem_limit: 800m
    mem_reservation: 300m
    volumes:
     - "sqldata-db:/var/opt/mssql/data:rw"
    environment:
      - SA_PASSWORD=Numsey@Password!
      - ACCEPT_EULA=Y
    ports:
      - "1401:1433"
    networks:
      - development-network
volumes:
  sqldata-db: {}
networks:
    development-network:
        driver: bridge